import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'logo': 'MessageMe',
          'name': 'UserName',
          'email': 'Email',
          'chats': 'Chats',
          'chat': 'Chat',
          'people': 'People',
          'stories': 'Stories',
          'myStory': 'MyStory',
          'story': 'Story',
          'settings': 'Settings',
          'myProfile': 'My Profile',
          'msg': 'Message',
          'msgs': 'Messages',
          'react': 'Reaction',
          'reacts': 'Reactions',
          'mood': 'Dark Mood',
          'status': 'Active Status',
          'lang': 'Language',
          'en': 'English',
          'ar': 'Arabic',
          'addGroup': 'Create New Group',
          'groupName': 'Group Name',
          'groupContains': 'Group should contains at least two members',
          'nameExist': 'This name is already exist',
          'accountPrivacy': 'Account Privacy',
          'profilePicture': 'Profile Picture',
          'storyPrivacy': 'Story Privacy',
          'displayedAccounts': 'Displayed Accounts',
          'blockedPeople': 'Blocked People',
          'phone': 'Phone number',
          'phone': 'Phone number',
          'caption': 'Caption',
          'txt': 'Text',
          'on': 'on',
          'off': 'off',
          'no': 'No',
          'to': 'to',
          'send': 'Send',
          'add': 'Add',
          'upload': 'Upload',
          'confirm': 'Confirm',
          'cancel': 'Cancel',
          'delete': 'Delete',
          'edit': 'Edit',
          'forward': 'Forward',
          'reply': 'Reply',
          'join': 'Joined',
          'block': 'Block',
          'unBlock': 'Un Block',
          'blockDec':
              'If you blocked this user, you will not be able to contact with or see stories',
          'youBlocked': 'You blocked',
          'viewed': 'Viewed By',
          'public': 'Public',
          'allUsers': 'All users',
          'contacts': 'Contacts',
          'contactsExcept': 'Contacts except..',
          'confirmDel': 'Are you sure to delete ',
          'whoISee': 'Who I can see',
          'whoSeeMe': 'Who can see my story',
          'whoSeeStory': 'Who can see my story',
          'whoSeeProfile': 'Who can see my profile',
          'whoSeePhone': 'Who can see my phone number',
          'whoSeePhoto': 'Who can see my profile picture',
          'searchBy': 'Search by name or email',
          'noNet': 'No Internet',
          'online': 'Online',
          'offline': 'Offline',
          'load': 'Loading...',
          'wait': 'Please wait!',
          'done': 'Action done',
          'err1': 'Error',
          'err2': 'Something went wrong',
          'failed': 'Process Failed',
          'tryAgain': 'Please try again later',
          'enter': 'Please enter your',
          'typeSomething': 'Type something',
          'data': 'Data',
          'type': 'Type...',
          'photo': 'Photo',
          'photos': 'Photos',
          'voice': 'Voice',
          'video': 'Video',
          'videos': 'Videos',
          'file': 'File',
          'record': 'Record',
          'location': 'Location',
          'verify': 'Verification Code',
          'code': 'Code',
          'member': 'member',
          'members': 'members',
          'change': 'Change',
          'backColor': 'Background Color',
          'backImg': 'Background Image',
          'mainColor': 'Main Color',
          'logout': 'LogOut',
          'logoutDec': 'Are you sure to leave the app',
          'yesterday': 'Yesterday'
        },
        'ar': {
          'logo': 'مسدج مي',
          'name': 'اسم المستخدم',
          'email': 'البريد الالكتروني',
          'chats': 'الدردشات',
          'chat': 'الدردشة',
          'people': 'الاشخاص',
          'stories': 'الحالات',
          'myStory': 'حالتي',
          'story': 'حالة',
          'settings': 'الاعددات',
          'myProfile': 'ملفي الشخصي',
          'msg': 'رسالة',
          'msgs': 'رسائل',
          'react': 'تفاعل',
          'reacts': 'تفاعل',
          'mood': 'الوضع الليلي',
          'status': 'نشط',
          'lang': 'اللغة',
          'en': 'الانجليزية',
          'ar': 'العربية',
          'addGroup': 'انشاء مجموعة',
          'groupName': 'اسم المجموعة',
          'groupContains': 'يجب ان تحتوي المجموعة علي عضوين علي الاقل',
          'nameExist': 'هدا الاسم موجود بالفغل',
          'accountPrivacy': 'خصوصية الحساب',
          'profilePicture': 'صورة الحساب ',
          'storyPrivacy': 'خصوصية الحالة',
          'displayedAccounts': 'اظهار الحساب',
          'blockedPeople': 'الاشخاص المحظورين',
          'phone': 'رقم الهاتف',
          'caption': 'عنوان',
          'txt': 'نص',
          'on': 'مفعل',
          'off': 'مغلق',
          'no': 'لا يوجود',
          'to': 'الي',
          'send': 'ارسال',
          'add': 'اضافة',
          'upload': 'رفع',
          'confirm': 'تاكيد',
          'cancel': 'الغاء',
          'delete': 'حدف',
          'edit': 'تعديل',
          'reply': 'رد',
          'join': 'التحق',
          'block': 'حظر',
          'unBlock': 'الغاء الحظر',
          'youBlocked': 'لقد حظرت',
          'blockDec':
              'إذا قمت بحظر هذا المستخدم ، فلن تتمكن من ارسال او استقبال اي رسائل او حالات',
          'public': 'العامة',
          'allUsers': 'جميع المستخدمين',
          'contacts': 'جهات اتصال',
          'contactsExcept': 'جهات اتصال باستثناء',
          'confirmDel': 'هل انت متاكد من حدف',
          'whoISee': 'من يمكنني رؤية حسابه',
          'whoSeeMe': 'من يمكنه رؤية حسابي',
          'whoSeeStory': 'من يستطيع رؤية فصتي',
          'whoSeeProfile': 'من يستطيع رؤية حسابي',
          'whoSeePhone': 'من يمكنه رؤية رقم هاتفي',
          'whoSeePhoto': 'من يستطيع رؤية صورتي الشخصية',
          'searchBy': 'البحث بالاسم أو البريد الإلكتروني',
          'noNet': 'لا يوجد اتصال لا بالانترنت',
          'online': 'متصل',
          'offline': ' غير متصل',
          'load': 'جاري التحميل',
          'wait': 'يرجي الانتظار',
          'done': 'تمت العملية',
          'err1': 'خطأ',
          'err2': 'هناك خطأ ما',
          'failed': 'فشلت العملية',
          'tryAgain': 'الرجاء المحاولة في وقت لاحق',
          'enter': 'من فضلك أدخل',
          'typeSomething': 'اكتب شيئا',
          'data': 'البيانات',
          'type': 'اكتب',
          'photo': 'صورة',
          'photos': 'صور',
          'voice': 'صوت',
          'videos': 'فيديوهات',
          'file': 'ملف',
          'record': 'مقطع صوتي',
          'location': 'الموقع',
          'verify': 'رمز التحقق',
          'code': 'رمز التحقق',
          'member': 'عضو',
          'members': 'اعضاء',
          'change': 'تغيير',
          'backColor': 'لون الخلفية',
          'backImg': 'صورة الخلفية',
          'mainColor': 'اللون المفضل',
          'logout': 'تسجيل خروج',
          'logoutDec': 'هل أنت متأكد من مغادرة التطبيق',
          'yesterday': 'امس'
        }
      };
}
